### ISSUE TITLE
Syncing no longer works

### ISSUE THREAD

**Issue by simonvanderveldt** [jorgicio/jorgicio-gentoo-overlay#261] opened 2020-11-15 08:36 UTC
Hi Jorge,

I'm not sure why but syncing your overlay no longer works/breaks syncing of all my repos
```
$ eix-sync
 * Running emerge --sync
...
>>> Syncing repository 'jorgicio' into '/var/db/repos/jorgicio'...
/usr/bin/git fetch origin
fatal: couldn't find remote ref refs/heads/master
!!! git fetch error in /var/db/repos/jorgicio
...

Action: sync for repo: jorgicio, returned code = 128

 * emerge --sync failed
```

**Comment by jorgicio** [comment] 2020-11-15 16:54
Yeah, sorry for not mention it on the README, but I will. I changed the main branch from `master` to `main`, so you just have to remove this repo and add it again.

I hope it helps.

**Comment by simonvanderveldt** [comment] 2020-11-15 20:08
Ah, OK, that explains it. Deleting it and then syncing again did indeed work/fix it.
I don't know how many users there are of your overlay but you might want to add a not or pin an issue about this change for them :)

**Comment by redblade7** [comment] 2020-11-15 23:58
I'm still having problems on one of my computers even after eselect disabling/enabling the repository multiple times. It gives the error "Please tell me who you are." during sync and asks me to set global user.name and user.email with git. I'd rather not override user git settings...

**Comment by Androphin** [comment] 2020-11-20 09:03
What's the reason for a need in changing branch from `master` to `main`?

**Comment by jorgicio** [comment] 2020-11-20 17:13
> I'm still having problems on one of my computers even after eselect disabling/enabling the repository multiple times. It gives the error "Please tell me who you are." during sync and asks me to set global user.name and user.email with git. I'd rather not override user git settings...

Did you try to use the remove option or the disable? You should remove because it deletes all files and then enable it and sync it and the issue should be resolved.

> Ah, OK, that explains it. Deleting it and then syncing again did indeed work/fix it.
> 
> I don't know how many users there are of your overlay but you might want to add a note to the readme or pin an issue about this change for them :)

Yes, I just did it in the README for users and collaborators.

> What's the reason for a need in changing branch from `master` to `main`?

I'm trying to use to the idea of the [changing name by Github](https://www.techrepublic.com/article/github-to-replace-master-with-main-starting-in-october-what-developers-need-to-know/). Of course I could to keep the `master` name, but I just created another repo for a personal project and now it uses the `main` name instead of `master`. So I'm trying to, when I push the changes, use the same command as I could.

**Comment by redblade7** [comment] 2020-11-20 22:01
> > I'm still having problems on one of my computers even after eselect disabling/enabling the repository multiple times. It gives the error "Please tell me who you are." during sync and asks me to set global user.name and user.email with git. I'd rather not override user git settings...
> 
> Did you try to use the remove option or the disable? You should remove because it deletes all files and then enable it and sync it and the issue should be resolved.
> 

I wasn't familiar with eselect repository remove. Works after remove, enable, and sync. Thank you!

**Comment by jorgicio** [comment] 2020-11-21 14:38
No problem!

As the issue is solved and changes are mentioned in my repo, I'm closing this.

**Closed by jorgicio** 2020-11-21 14:38 UTC
Labels: repo issues
